[pytest]

testpaths = tests
pythonpath = .

addopts = -v -ra --strict-markers --cov=app --cov=utils --cov-report=term --cov-report=html

markers = 
    slow: slow tests
    model: tests related to ml model
    api: API route tests
    utils: utility function tests
