[pytest]

testpaths = tests
pythonpath = .

addopts = -v -ra --strict-markers

markers = 
    slow: slow tests
    model: tests related to ml model
    api: API route tests
    utils: utility function tests
